spring:
  rabbitmq:
    host: 39.103.233.82
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
  datasource:
    username: socialCircle
    password: socialCircle123
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.103.233.82:3306/social_circle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    host: 39.103.233.82
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
  data:
    mongodb:
      uri: mongodb://39.103.233.82:27017/msg
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

com:
  socialCircle:
    tokenKey: webpomlwjshpp
    email:
      addr: 210579781@qq.com
      password: fdxmyiymilohbgjc
      host: smtp.qq.com

    chat:
      url: "http://127.0.0.1:10333"